### ISSUE TITLE
Update for murr_mine_server

### ISSUE THREAD

**Issue by Murrengan** [Andrey-Kuzmichev/MineServ-plugin-archive#1]
- set return coordinates 120  66  -210
- create return compas from planks и dirt 
- add config_plugin_murr.yml (set coordinates from it as example)

**Comment by Andrey-Kuzmichev** [comment]
**Done! Enjoy it!**

- [x] set return coordinates 120 66 -210
- [x] create return compas from planks и dirt
- [x] add config_plugin_murr.yml (set coordinates from it as example)
